workflows:
  android-workflow:
    name: Android Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Set up Flutter
        script: |
          flutter --version
          flutter doctor
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build APK
        script: |
          flutter build apk --release --split-per-abi
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com # Change this to your email
